services:
  - type: web
    name: flask-api
    env: python
    plan: free
    buildCommand: |
      chmod +x stockfish-linux/stockfish
      pip install -r requirements.txt
    startCommand: python api.py
    region: oregon
    branch: main
    rootDir: stockfish_api